ALTER TABLE livemap_data 
MODIFY COLUMN last_connect TIMESTAMP NULL,
ADD COLUMN last_dead_position VARCHAR(32) NULL,
ADD COLUMN skill_agriculture INT(8) NULL,
ADD COLUMN skill_cardio INT(8) NULL,
ADD COLUMN skill_cooking INT(8) NULL,
ADD COLUMN skill_crafting INT(8) NULL,
ADD COLUMN skill_dexerity INT(8) NULL,
ADD COLUMN skill_diving INT(8) NULL,
ADD COLUMN skill_engineer INT(8) NULL,
ADD COLUMN skill_exercise INT(8) NULL,
ADD COLUMN skill_fishing INT(8) NULL,
ADD COLUMN skill_healing INT(8) NULL,
ADD COLUMN skill_immunity INT(8) NULL,
ADD COLUMN skill_mechanic INT(8) NULL,
ADD COLUMN skill_outdoors INT(8) NULL,
ADD COLUMN skill_overkill INT(8) NULL,
ADD COLUMN skill_parkour INT(8) NULL,
ADD COLUMN skill_sharpshooter INT(8) NULL,
ADD COLUMN skill_sneakybeaky INT(8) NULL,
ADD COLUMN skill_strength INT(8) NULL,
ADD COLUMN skill_survival INT(8) NULL,
ADD COLUMN skill_toughness INT(8) NULL,
ADD COLUMN skill_vitality INT(8) NULL,
ADD COLUMN skill_warmblooded INT(8) NULL,
ADD COLUMN last_refresh TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
ADD COLUMN last_disconnect TIMESTAMP NULL,
ADD COLUMN total_playtime INT(8) NOT NULL DEFAULT 0;